-- Migration: Add call_quality_analysis column
-- Date: 2025-01-20
-- Author: Claude
-- Risk: LOW (adds column, no data loss)
--
-- Context:
-- Adds a TEXT column to store detailed analysis of call_quality_score.
-- This complements the numeric score with human-readable explanation.
--
-- Changes:
-- 1. Add call_quality_analysis column (TEXT)
-- 2. Add full-text search index for future search features
-- 3. Add column comment for documentation
--
-- Expected Impact:
-- - Dipler can store detailed quality analysis
-- - Dashboard can display analysis in tooltips/modals
-- - Exports include detailed scoring rationale

BEGIN;

-- =====================================================
-- Step 1: Add call_quality_analysis column
-- =====================================================

ALTER TABLE agent_calls
  ADD COLUMN IF NOT EXISTS call_quality_analysis TEXT;

-- Add comment for documentation
COMMENT ON COLUMN agent_calls.call_quality_analysis IS
  'Detailed analysis for call_quality_score (0-100).
  Generated by Dipler post-conversation analysis.
  Format: DÉTAIL DES POINTS / POINTS FORTS / AXES D''AMÉLIORATION.
  Example: "Durée: 95s → 25/25 pts | Sentiment: positif → 30/30 pts..."';

-- =====================================================
-- Step 2: Add full-text search index (French)
-- =====================================================

-- GIN index for full-text search on analysis
-- Useful for filtering calls by specific issues (e.g., "latence élevée")
CREATE INDEX IF NOT EXISTS idx_agent_calls_quality_analysis_fts
  ON agent_calls USING gin(to_tsvector('french', call_quality_analysis))
  WHERE call_quality_analysis IS NOT NULL;

-- B-tree index for checking presence of analysis
CREATE INDEX IF NOT EXISTS idx_agent_calls_has_analysis
  ON agent_calls(started_at DESC)
  WHERE call_quality_analysis IS NOT NULL;

-- =====================================================
-- Step 3: Statistics
-- =====================================================

DO $$
DECLARE
  v_total_calls INTEGER;
  v_calls_with_score INTEGER;
  v_calls_with_analysis INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_total_calls FROM agent_calls;
  SELECT COUNT(*) INTO v_calls_with_score FROM agent_calls WHERE call_quality_score IS NOT NULL;
  SELECT COUNT(*) INTO v_calls_with_analysis FROM agent_calls WHERE call_quality_analysis IS NOT NULL;

  RAISE NOTICE '=== QUALITY SCORING STATISTICS ===';
  RAISE NOTICE 'Total calls: %', v_total_calls;
  RAISE NOTICE 'Calls with quality score: % (%.1f%%)',
    v_calls_with_score,
    CASE WHEN v_total_calls > 0 THEN (v_calls_with_score::numeric / v_total_calls * 100) ELSE 0 END;
  RAISE NOTICE 'Calls with analysis: % (%.1f%%)',
    v_calls_with_analysis,
    CASE WHEN v_total_calls > 0 THEN (v_calls_with_analysis::numeric / v_total_calls * 100) ELSE 0 END;
  RAISE NOTICE '===';
END $$;

COMMIT;

-- ===================================
-- VERIFICATION QUERIES (commented out)
-- ===================================

-- Test 1: Check column exists
-- SELECT
--   column_name,
--   data_type,
--   is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'agent_calls'
--   AND column_name = 'call_quality_analysis';

-- Test 2: Check existing data
-- SELECT
--   id,
--   started_at,
--   call_quality_score,
--   call_quality_analysis
-- FROM agent_calls
-- WHERE call_quality_analysis IS NOT NULL
-- ORDER BY started_at DESC
-- LIMIT 5;

-- Test 3: Test full-text search (after data is populated)
-- SELECT
--   id,
--   started_at,
--   call_quality_score,
--   call_quality_analysis
-- FROM agent_calls
-- WHERE to_tsvector('french', call_quality_analysis) @@ to_tsquery('french', 'latence | lent')
-- ORDER BY started_at DESC
-- LIMIT 10;

-- Test 4: Check index usage
-- EXPLAIN ANALYZE
-- SELECT COUNT(*)
-- FROM agent_calls
-- WHERE call_quality_analysis IS NOT NULL;

-- Test 5: Sample insert for testing
-- INSERT INTO agent_calls (
--   deployment_id,
--   started_at,
--   duration_seconds,
--   outcome,
--   emotion,
--   call_quality_score,
--   call_quality_analysis
-- ) VALUES (
--   '348cc94d-b4e8-4281-b33a-bc9378fecffc',
--   NOW(),
--   95,
--   'appointment_scheduled',
--   'positive',
--   97,
--   'DÉTAIL DES POINTS :
-- - Durée : 95 secondes → 25/25 points
-- - Sentiment : positif → 30/30 points
-- - Résultat : Rendez-vous programmé → 30/30 points
-- - Latence LLM : 650ms → 7/10 points
-- - Latence TTS : 280ms → 5/5 points
-- Total : 97/100
--
-- POINTS FORTS :
-- - Rendez-vous obtenu avec sentiment positif du client
-- - Durée optimale permettant une conversation complète
-- - Génération audio fluide (TTS < 300ms)
--
-- AXES D''AMÉLIORATION :
-- - Latence LLM légèrement au-dessus de l''optimal (650ms vs 500ms cible)'
-- );
